backend:
  name: git-gateway
  branch: master

# Alternative local backend for testing (uncomment to use)
# backend:
#   name: test-repo
#   branch: master

# Media storage (optional)
media_folder: "images" # Media files will be stored in the repo under images/
public_folder: "images" # The src attribute for uploaded media will begin with /images/

# Collections
collections:
  # Events collection
  - name: "events"
    label: "Events"
    folder: "content/events"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Time", name: "time", widget: "string", hint: "e.g., 09:00 AM - 05:00 PM"}
      - {label: "Location", name: "location", widget: "string"}
      - {label: "Instructor", name: "instructor", widget: "string", required: false}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Additional Info", name: "additional", widget: "text", required: false}
      - label: "Category"
        name: "category"
        widget: "select"
        options:
          - {label: "Training", value: "training"}
          - {label: "Workshop", value: "workshop"}
          - {label: "Meeting", value: "meeting"}
          - {label: "Conference", value: "conference"}
      - {label: "Published", name: "published", widget: "boolean", default: true}
